### PR TITLE
To-do-list: JS Best Practices

### PR DESCRIPTION
**Pull request by tugsem**
## Hello there, Thanks for your feedback ✊

### CODE REVIEW

**Review by GedeonTS — CHANGES_REQUESTED** [review]
Hi @tugsem 

You have done a great job so far! 
there are just a few things you can fix to make it even better.


# (Highlights) Good points
The pull request follows the Github workflow
There are no YAGNI, and KISS issues
# [Required] suggestions:
 - Kindly try to fix the live link in your readme file, the app inside is not working as expected.
# [Optional] suggestions:
 - It would be better if you added comments in your code because it would make it easier to understand for others.

Cheers and Happy coding!👏👏👏

**Comment by tugsem** [comment]
> Hi @tugsem
> 
> You have done a great job! there are just a few things you can fix to make it even better.
> 
> # (Highlights) Good points
> The pull request is following the Github workflow There are no YAGNI, and KISS issues
> 
> # [Required] suggestions:
> * Kindly try to fix the life in your readme file, the app inside is not working as expected.
> 
> # [Optional] suggestions:
> * It would be if you added comments in your code so it would be easier to understand for others,

Hi @GedeonTS 
Thank you for highlighting these issues. But I couldn't get what you were saying. The live link is working fine on my browser.

**Comment by tugsem** [comment]
@GedeonTS 👍

**Review by GedeonTS — APPROVED** [review]
Hi @tugsem 

Good job! it's time to merge it!

# (Highlights) Good points

The live demo is working perfectly.
The pull request is following the Github workflow.
There are no YAGNI, and KISS issues.

# [Optional] suggestions
Just a few improvements on the functionality which made me think the demo was incomplete
 - in addition to the trigger button the input listener must also open on pressing the button "Enter", something like:
 ```
 input.addEventListener('keypress', (e) => {
  if (e.key === 'Enter') {
```

**Pull request merged**
